export enum CATEGORY_ICON {
    SHOPPING = 'cart-shopping',
    HOME = 'house',
    BOOK = 'book',
    GIFT = 'gift',
    CAR = 'car',
    MUSIC = 'music',
    GAME = 'gamepad',
    LAPTOP = 'laptop',
    HEART = 'heart',
    CAMERA = 'camera',
    PAW = 'paw',
    UTENSILS = 'utensils',
    PHONE = 'phone',
    BICYCLE = 'bicycle',
    BOLT = 'bolt',
    SHIRT = 'shirt',
    SHOE_PRINT = 'shoe-prints',
    HAT_COWBOY = 'hat-cowboy',
    BAG_SHOPPING = 'bag-shopping',
    GLASSES = 'glasses',
    RING = 'ring',
    NECKLACE = 'gem',
    SOCKS = 'socks',
    VOLLEYBALL = 'volleyball'
}
